FROM openjdk:11.0.7-jre-slim

RUN apt-get update
RUN apt-get install -y  zip \
    unzip \
RUN apt-get install curl wget
RUN adduser -u 1001 -h /home/sunbird/mvc-service -D sunbird \
RUN mkdir -p /home/sunbird/mvc-service

RUN chown -R sunbird:sunbird /home/sunbird/mvc-service
USER sunbird
COPY ./mvc-api/search-service/target/search-service-1.0-SNAPSHOT-dist.zip /home/sunbird/mvc-service/
RUN unzip /home/sunbird/mvc-service/search-service-1.0-SNAPSHOT-dist.zip -d /home/sunbird/mvc-service/
RUN rm /home/sunbird/mvc-service/search-service-1.0-SNAPSHOT-dist.zip
COPY --chown=sunbird ./schemas /home/sunbird/mvc-service/search-service-1.0-SNAPSHOT/schemas
WORKDIR /home/sunbird/mvc-service/
CMD java  -cp '/home/sunbird/mvc-service/search-service-1.0-SNAPSHOT/lib/*' -Dconfig.file=/home/sunbird/mvc-service/search-service-1.0-SNAPSHOT/config/application.conf play.core.server.ProdServerStart /home/sunbird/mvc-service/search-service-1.0-SNAPSHOT
